### ISSUE TITLE
You don't seem to have any data at the moment

### ISSUE THREAD

**Issue by johnkattenhorn** [richorama/SiloMon#1]
I've configured SiloMon to look at our storage account for both our development and test environments.

SiloMon correctly reports the names and configurations correctly so must be ready the information but selecting the name in the overview always returns `You don't seem to have any data at the moment`.

Did I miss a step ? Do I need to configure or deploy some additional code into the Orleans application ?

**Comment by richorama** [comment]
Hi John, thanks for reporting this (and thanks for using SiloMon!)

I think this is a result of the way stats are now reported in Orleans, and SiloMon is still expecting them in the old format.

I'll fix this up shortly...

**Comment by johnkattenhorn** [comment]
Thanks Richard, Ah of course, I forgotten there had a bunch of changes recently. Let me know if you want be to do a pull against a branch and we'd happily do some testing.

**Comment by richorama** [comment]
@johnkattenhorn I have updated the site so it should show the metrics now. It shows the last 1000 data points collected by the system. I'll work on improving the UI over time, but it would be useful to get some initial feedback to see if it works for you!

**Comment by johnkattenhorn** [comment]
Yep, I can see some data, very cool! Thanks @richorama, we use it of the next couple of days and come back with some initial food for thought.

See you at the hangout on Friday :-)

**Comment by richorama** [comment]
thanks - see you then!
